
// Array of words to choose from
const questions = ["How can we find and produce enough safe foods for us all to survive?", 
"What is the best way to build and shelter ourselves from the elements?", 
"What are the greatest dangers and how can we protect ourselves?", 
"What are the most effective ways to heal injuries and illnesses?", 
"How can we best raise and educate our children?", 
"How should we organise our society and make collective decisions?", 
"How can we resolve conflicts fairly and justly?", 
"How can we improve our tools and technologies sustainably?", 
"How can we effectively communicate with others?", 
"How can we predict and prepare for natural disasters?", 
"What may be the meaning and purpose of life as a whole?", 
"Is there a god or higher power, and if so, what is its nature?", 
"What may be the nature of reality and our place in it?", 
"What could knowledge be and how may we find and best use it?", 
"What is love - and what are its forms and purpose?", 
"What does it mean to be brave to become braver still?", 
"What is beauty and how to be beautiful best?", 
"What is goodness and so how should we live?", 
"What is justice and how should we apply it?", 
"What may happen after we die?", 
"What exactly is the Universe?", 
"What may be the history of the Universe - its age and origin?", 
"What does the Universe seem to be made of - its components and proportions?", 
"How large might the Universe be and what defines its boundaries, if any?", 
"Which models explain the Universe’s structure and movement?", 
"How may the first stars and galaxies have formed from early gases?", 
"What role does our galaxy play in the context of the entire Universe?", 
"What drives the apparent expansion of the Universe?", 
"What could be the far future of the Universe?", 
"Does the Universe have a purpose - one, none, many? ", 
"What exactly is the Earth - its place and purpose?", 
"What may be the history of the Earth - its age and origin?", 
"What is Earth made of - its size and structure?", 
"What is the air around us made of?", 
"How are Earth's land and water distributed?", 
"What primarily causes earthquakes and volcanoes?", 
"What causes the seasons?", 
"What causes the day and night cycle?", 
"Why do we have a Moon and how does it affect us?", 
"What could be the far future of the Earth itself?", 
"What exactly is life, and what makes something alive?", 
"What may be the history of all life - its age and origins?", 
"How might life have emerged from non-living matter, if it did at all?", 
"What are the basic units of life, and how do they function?", 
"How diverse is life on Earth in terms of species and forms?", 
"How does life reproduce and pass on genetic information?", 
"What mechanisms drive the evolution and adaptation of life?", 
"Why does it seem that most species that ever existed became extinct?", 
"What are the key threats to biodiversity on Earth today?", 
"Is there life beyond Earth, and how can we search for it? ", 
"What exactly is science - its purpose and essence?", 
"What are the main branches of science, and how do they combine?", 
"What may be the history of science - its origins and key revolutions?", 
"How does the scientific method advance our understanding of the world?", 
"What are the key theories that have shaped modern science?", 
"How does mathematics interplay with science to make predictions?", 
"How has science influenced human society, and daily life?", 
"What ethical considerations are important in scientific research?", 
"How does science contribute to environmental stewardship?", 
"What could be the future of science and its potential impact on humanity?", 
"What exactly is technology - its purpose and essence?", 
"What are the main types of technology and their primary applications?", 
"What may be the history of technology - its milestones and evolution?", 
"How has technology shaped human civilization and daily life?", 
"What are the best inventions and why?", 
"Which are the most important emerging technologies and why?", 
"What are the biggest ethical issues from technological advancements?", 
"Which technologies are most responsible for worsening the environment?", 
"Which technologies are most capable of fixing the environment?", 
"Could technology have evolved profoundly differently? ", 
"What exactly is art - its purpose and essence?", 
"What are the main branches and forms of art - and how do they combine?", 
"What may be the history of art - its origins and evolution?", 
"What do people try to communicate using art?", 
"How can one best create and appreciate art?", 
"How are art styles and movements currently categorized, and why?", 
"What role do museums play in preserving art and culture?", 
"How does technology, including AI, impact the creation and perception of art?", 
"What ethical issues surround art, such as appropriation and censorship?", 
"What challenges our conception of art?", 
"What exactly is language - human or otherwise?", 
"What may be the history of language - its origins and development?", 
"How many languages might exist, and how can they be counted?", 
"How are languages classified into families and groups?", 
"How do languages change over time?", 
"What appears to make human language unique compared to other communication forms?", 
"How does language influence and reflect culture?", 
"What factors contribute to language extinction and preservation?", 
"How does the human brain acquire and process language?", 
"What role does technology play in language use and evolution?", 
"Who are humans - their defining characteristics and essence?", 
"What may be the overall history of humans - their origins and evolution?", 
"How did the shift from nomadic life to agriculture shape societies?", 
"What key traits distinguish humans from other species?", 
"How do humans organise socially, and what values emerge from this?", 
"How genetically similar are humans, and what accounts for diversity?", 
"What unique abilities allow humans to impact the world significantly?", 
"How has human population growth affected the planet?", 
"What are the key achievements and challenges of space exploration?", 
"What could be the far future of humanity?", 
"What exactly is civilization - its characteristics and purpose?", 
"What may be the history of civilization - its various origins and major developments?", 
"How have different civilizations evolved and interacted over time?", 
"What are the common structures of governments and economies?", 
"How do legal and political systems vary across the world?", 
"What are the major achievements and contributions of civilizations?", 
"How has globalisation influenced modern civilizations?", 
"What are the key challenges facing civilizations today?", 
"How do civilizations address global risks like climate change and conflict?", 
"What could be the future of civilization amid technological and social changes?", 
"What exactly is religion - its essence and role in human life?", 
"What may be the history of religion - its origins and evolution?", 
"What are the major religions of the world and their core beliefs?", 
"How do religious beliefs and practices vary across cultures?", 
"What functions does religion serve in societies?", 
"How have religions influenced human history and culture?", 
"What challenges arise from religious pluralism and coexistence?", 
"How does secularism interact with religious traditions?", 
"What issues stem from religious extremism, and how are they addressed?", 
"How might religion evolve in response to global changes?"];



const conditions = ["Answer as though you're a walking encyclopedia.", 
"Answer as if the entire world were watching and listening to you.", 
"Answer in the style of a dusty academic book.", 
"Answer in an incredibly formal and professional style.", 
"Answer with quotes and attributions (according to...).", 
"Answer as though you were delivering a university lecture.", 
"Answer as if you and your listener were excessively, effusive enthusiasts.", 
"Answer as if in a high-level discourse with experts.", 
"Answer with a rich, literary flare.", 
"Answer in essay form.", 
"Answer with an image (a chart or some other visual).", 
"Answer offering balanced information to a divided audience.", 
"Answer from two very distinct perspectives.", 
"Answer while making it very relevant to the present.", 
"Answer in a detached, impersonal fashion.", 
"Answer with several follow-up questions.", 
"Answer as if in a media interview.", 
"Answer using metaphor, simile, or personification.", 
"Answer by telling a short story.", 
"Answer as if you were an alien.", 
"Answer as though asked by a five-year-old.", 
"Answer as though asked by a ninety-year-old.", 
"Answer in a poetic style.", 
"Answer using the rarest, longest, and weirdest words you can.", 
"Answer as if trying to please the most argumentative person ever.", 
"Answer as if you were the smartest being in the Universe.", 
"Answer in the most meaningful five-word sentence you can.", 
"Answer as if you were a well-meaning fool.", 
"Answer as if you were on a popular television show.", 
"Answer as a fictional character like Sherlock Holmes.", 
"Answer as a historical figure like Albert Einstein.", 
"Answer as if you always speak in riddles.", 
"Answer using as many one syllable words as you can.", 
"Answer like a jargon-heavy expert.", 
"Answer in one minute.", 
"Answer with levity.", 
"Answer as if you were writing a journal to yourself.", 
"Answer as if it were the most obvious question ever.", 
"Answer as if it were the hardest question you've ever been asked.", 
"Answer as if you were trying to explain to an ancestral human."];

// Function to change the text
function changeText() {
    // Get the span element (assuming it has an id of 'textSpan')
    const questionSpan = document.getElementById('question');
    const conditionSpan = document.getElementById('condition');
    
    // Choose a random word from the array
    const randomQuestion = questions[Math.floor(Math.random() * questions.length)];
    const randomCondition = conditions[Math.floor(Math.random() * conditions.length)];
    
    // Set the span's inner text to the random word
    question.innerText = randomQuestion;
    condition.innerText = randomCondition;
}

// Call the function when the page loads
window.onload = changeText;

// Optional: You can also set up a button to trigger the change
// Uncomment the next line if you want to use a button with id 'changeButton'
// document.getElementById('changeButton').addEventListener('click', changeText);